### ISSUE TITLE
Feature Request non admin roles.

### ISSUE THREAD

**Issue by stefan1968** [dwaring87/directus-extension-publish-netlify#2]
Would it be possible to enable this extension for non-admin roles, some of the 'editors' in my project can be trusted to initiate a netlify deploy. 

Maybe some environment variable?

**Comment by dwaring87** [comment]
This is a good question.  The module uses some of the internal Directus API endpoints, so I'll have to check what permissions are required for those (otherwise you might need to add access to some of the directus tables for your 'editor' role).

**Comment by dwaring87** [comment]
It looks like roles that have 'app access' have the permissions required for the module to work, so this should be feasible.  I'll work on adding an environment variable that can specify additional roles that are allowed to access the module.

**Comment by dwaring87** [comment]
See [Configuration section in README](https://github.com/dwaring87/directus-extension-publish-netlify#enabled-roles)
