### ISSUE TITLE
Setup Error post deploy hook

### ISSUE THREAD

**Issue by malteludwig** [dwaring87/directus-extension-publish-netlify#3]
Trying to create a post deploy-hook gives an error: API request failed.

<img width="642" alt="Screenshot 2022-07-12 at 13 59 03" src="https://user-images.githubusercontent.com/40273858/178485276-7c34b5ce-af3e-4906-8d8a-c5f0a15d36cb.png">

is that a misconfiguration my side? everything else works fine.

Thanks for that extension, really helpful!

**Comment by dwaring87** [comment]
Thanks for reporting this.  Can you tell what version of Directus you're using?

I can't replicate this exact error, but it looks like an update to Directus has changed how the user's Token is accessed through the API.

**Comment by malteludwig** [comment]
Yes sorry, its  v 9.14.1
I’ve not used extension before so couldn’t tell if there was a breaking change in direct us.

**Comment by dwaring87** [comment]
I've fixed this by removing the usage of the Netlify post-deploy hook entirely.  Let me know if there are still any issues with the Setup.
